version: '3'
services:
  web:
    image: java_springv1_t5
    build: .
    ports:
      - "8015:8015"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/team5/volumes
